### ISSUE TITLE
通信参数

### ISSUE THREAD

**Issue by gxh-apologize** [kongqw/KqwSerialPortDemo#12]
校验位:N，数据位:8，停止位:1，请问这些参数怎么设置呢？不设置的话会有影响吗？

**Comment by ChenArno** [comment]
@gxh-apologize 你没问完就关闭了，我也有这个疑问

**Comment by gxh-apologize** [comment]
是这样的，我是有这个疑问的，看了一些资料，有人说收到的数据会有影响，有人说默认就是N81，我使用了作者这个库，没有设置N81，对一个串口发命令开门，反正是成功了，项目急，也就没有深究。后来我们根据要求换了厂家的jar包直接调用他们的方法控制串口。。所以我就关闭了这个问题。

**Comment by ChenArno** [comment]
感谢解答，
