### ISSUE TITLE
怎么突然就不能用了？

### ISSUE THREAD

**Issue by sasa2211** [kongqw/KqwSerialPortDemo#35]
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find AndroidSerialPort.aar (com.github.kongqw:AndroidSerialPort:1.0.1).
  Searched in the following locations:
      https://jitpack.io/com/github/kongqw/AndroidSerialPort/1.0.1/AndroidSerialPort-1.0.1.aar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Coulomb-engine** [comment]
我也遇到了同样的问题，这个issue作者不跟进了吗

**Comment by step-2017** [comment]
好像换人维护了！https://github.com/cl-6666/serialPort,用这个地址吧，可以吧他项目拉下来作为工程依赖。这样改动最小

**Comment by sasa2211** [comment]
好像换人维护了！https://github.com/cl-6666/serialPort,用这个地址吧，可以吧他项目拉下来作为工程依赖。这样改动最小

**Comment by step-2017** [comment]
> 我也遇到了同样的问题，这个issue作者不跟进了吗

- 

-
